/**:
  ros__parameters:
    # Basic setup
    map_frame: odom
    robot_frame: base_link
    max_range: 10.0
    resolution: 0.05
    prob_hit: 0.8
    prob_miss: 0.1
    thres_min: 0.12
    thres_max: 0.8
    map_save_dir: ""

    # Visualizations
    publish_pointcloud: true
    publish_vis_marker: true
    visualization_rate: 2.0

    # Sensor input
    apply_raw_sensor_data: false

    # Remote mapping
    publish_sections: false

    smooth_remote_sections: true
    remote_section_smoothing_iterations: 2

    remote_sources: [vdb_mapping]
    vdb_mapping:
      namespace: vdb_mapping
      apply_remote_sections: true
